export const ALL_POST_REQUEST="ALL_POST_REQUEST";
export const ALL_POST_SUCCESS="ALL_POST_SUCCESS";
export const ALL_POST_FAIL="ALL_POST_FAIL";

export const POST_REQUEST="POST_REQUEST";
export const POST_SUCCESS="POST_SUCCESS";
export const POST_FAIL="POST_FAIL";

export const REGISTER_POST_SUCCESS="REGISTER_POST_SUCCESS";
export const REGISTER_POST_FAIL="REGISTER_POST_FAIL";
export const REGISTER_POST_REQUEST="REGISTER_POST_REQUEST";