export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";

export const SIGNUP_USER_REQUEST="SIGNUP_USER_REQUEST";
export const SIGNUP_USER_FAIL="SIGNUP_USER_FAIL";
export const SIGNUP_USER_SUCCESS="SIGNUP_USER_SUCCESS";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_FAIL="GET_USER_FAIL";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";